### ISSUE TITLE
The lastLocation data is not updated fast enough for `componentDidUpdate` or `useEffect([])`

### ISSUE THREAD

**Issue by VoxBorealis** [donus3/react-last-location-router#4]
The timings seem to be different from the old version of reac-router-last-location. 

`import React, { useEffect } from 'react';
import { useLastLocation } from 'react-router-dom-last-location';

const TesterYea = () => {
  const { lastLocation } = useLastLocation();
  console.log('test');
  console.log(lastLocation);

  useEffect(() => {
    console.log('useEffect');
    console.log(lastLocation);
  }, []);
  return (
    <div>
      asd
    </div>
  );
};

export default TesterYea;`

E.g. here the lastLocation is not updated to the correct value inside the useEffect but on the last re-renders the value is updated. What causes this delay?

**Comment by donus3** [comment]
@VoxBorealis I cannot reduce using https://github.com/donus3/react-last-location-router/tree/main/example. Could you provide more context like how your router setup is or your example project?
